module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: data
    target: data
  - source: partials
    target: layouts/partials/tnd-blocks
  - source: console
    target: layouts/partials/tnd-blocks
